# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MeaLeon',
                'doc_host': 'https://AaronWChen.github.io',
                'git_url': 'https://github.com/AaronWChen/MeaLeon',
                'lib_path': 'MeaLeon'},
  'syms': {'MeaLeon.core': {'MeaLeon.core.foo': ('core.html#foo', 'MeaLeon/core.py')}}}
