"""tweak user/allergy relationship

Revision ID: 2cacca6e0ffd
Revises: 8d5108ccef84
Create Date: 2025-09-04 10:41:09.881847

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cacca6e0ffd"
down_revision = "8d5108ccef84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allergy")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergy",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("ingredient", sa.VARCHAR(length=140), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
