"""add language to reviews

Revision ID: caf31fb055b2
Revises: aca7395f7b7d
Create Date: 2025-10-02 22:48:52.367469

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "caf31fb055b2"
down_revision = "aca7395f7b7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
