[project]
name = "MeaLeon-Recommender-Service"
version = "0.1.1"
description = "This is the recommender service environment for MeaLeon. MeaLeon is a full stack data science project using machine learning, natural language processing, recommendation engine, and MLOps"
authors = [{ name = "Aaron W. Chen", email = "awc33@cornell.edu" }]
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi",
    "redis",
    "pydantic",
    "uvicorn",
    "httpx"
]